deploymentsGeneral:
  enableAffinity: false # default is true

# nameOverride: whoami

deployments:
  whoami:
    securityContext:
      runAsUser: 1000
      runAsGroup: 3000
      fsGroup: 2000
    containers:
    - name: whoami
      image: containous/whoami
      imageTag: v1.5.0
      resources:
        limits:
          cpu: 10m
          memory: 128Mi
        requests:
          cpu: 1m
          memory: 64Mi
      args:
        - --port
        - "8080"
      ports:
        - name: web
          containerPort: 8080
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true

services:
  whoami-web:
    type: ClusterIP
    ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 8080

ingresses:
  whoami.example.com:
    hosts:
    - paths:
      - serviceName: whoami-web
        servicePort: web
    certManager:
      issuerType: issuer
      issuerName: selfsigned-ca-issuer
      # originalIssuerName: letsencrypt

issuerType: ClusterIssuer

issuers:
  selfsigned-issuer:
    kind: "{{ .Values.issuerType }}"
    selfSigned: {}
  selfsigned-ca-issuer:
    ca:
      secretName: selfsigned-ca

certificates:
  selfsigned-ca:
    isCA: true
    commonName: selfsigned-ca
    privateKey:
      algorithm: ECDSA
      size: 256
    issuerRef:
      name: selfsigned-issuer
      kind: "{{ .Values.issuerType }}"

# helm install f ./charts/universal-chart --values ./samples/whoami-with-certs.yml
#